PUT http://localhost:3003/api/blogs/5f1a781ff017d34de26f7095
Content-Type: application/json

{
    "title": "2020 technology industry outlook",
    "author": "Deloitte",
    "url": "https://www2.deloitte.com/us/en/pages/technology-media-and-telecommunications/articles/technology-industry-outlook.html",
    "likes": 100
}